apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: klage-dittnav-pdfgen
  namespace: klage
  labels:
    team: klage
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: klage-arkiver-journalpost
        - application: klage-dittnav-api