name: Manual deploy to production
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}/klage-dittnav-pdfgen:${{ github.sha }}

jobs:
  deploy_to_prod:
    permissions:
      contents: write
    name: Deploy to prod
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
      - name: Generate release version
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=7 HEAD)
          VERSION=$TIME-$COMMIT
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - uses: ncipollo/release-action@main
        with:
          tag: ${{ env.VERSION }}
