name: Manual deploy to production
on:
  workflow_dispatch:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/klage-dittnav-pdfgen:${{ github.sha }}

jobs:
   deploy_to_prod:
      name: Deploy to prod
      if: github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@v1
         -  uses: nais/deploy/actions/deploy@v1
            env:
               APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
               CLUSTER: prod-gcp
               RESOURCE: nais.yaml